name: tests

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Install composer dependencies
        run: composer update --no-interaction --prefer-dist
      - name: Run Tests
        run: ./vendor/bin/pest
